export const archetypeDefs = {
  'Floor General': { tr: "Oyunu yöneten, pas önceliği yüksek, takımın karar mekanizması olan oyun kurucu.", en: "A pass-first point guard who runs the offense and serves as the team's decision-maker." },
  'Combo Guard': { tr: "Hem skor üretebilen hem oyun kurabilen, iki role de uyum sağlayan guard.", en: "A guard capable of both scoring and playmaking, comfortable in either role." },
  'Scoring Point Guard': { tr: "Asıl kimliği skor üretmek olan, hücumu genelde kendi eliyle bitiren oyun kurucu.", en: "A point guard whose primary identity is scoring, usually finishing possessions himself." },
  'Slasher': { tr: "Çembere agresif gidişleriyle öne çıkan, temas almaktan çekinmeyen guard.", en: "A guard who thrives attacking the rim aggressively and isn't afraid of contact." },
  'Sharpshooter': { tr: "Kimliğini büyük ölçüde dış şuttan alan, yüksek hacimli ve isabetli bir nişancı.", en: "A player whose identity is built primarily around high-volume, accurate outside shooting." },
  '3&D Wing': { tr: "Savunma ve dış şut üzerine kurulu, tamamlayıcı bir kanat profili.", en: "A wing built around defense and spot-up shooting, a complementary role player." },
  'Scoring Wing': { tr: "Kendi şutunu yaratabilen, hücumda birincil bir tehdit oluşturan kanat.", en: "A wing capable of creating his own shot and serving as a primary scoring threat." },
  'Point Forward': { tr: "Boy avantajını pas ve oyun kurma yeteneğiyle birleştiren, forvet pozisyonunda oynayan bir organizatör.", en: "A forward-sized player who combines his size with passing and playmaking ability." },
  'Athletic Forward': { tr: "Fiziksel gücünü ve atletizmini oyununun merkezine koyan, enerjik bir forvet.", en: "A high-energy forward whose game is built around physicality and athleticism." },
  'Stretch Big': { tr: "Sahayı açan, dış şut atabilen bir pivot ya da güç forvet.", en: "A center or power forward who can shoot from outside and space the floor." },
  'Athletic Center': { tr: "Fiziksel üstünlüğü ve sıçrama yeteneğiyle öne çıkan, geleneksel bir pivot.", en: "A traditional center defined by physical dominance and leaping ability." },
  'Rim Protector': { tr: "Asıl görevi çemberi korumak olan, savunma odaklı bir pivot.", en: "A defense-first center whose primary job is protecting the rim." },
  'Post Scorer': { tr: "Düşük post ve pick-and-roll bitirişlerinden skor üreten, şut menzili ya da elit savunma/atletizmle tanımlanmayan içeri oyuncusu.", en: "A big who scores from the low post and pick-and-roll finishes, not defined by outside shooting or elite defense/athleticism." },
};
